export const JOB_SEARCH_REQUEST = 'JOB_SEARCH_REQUEST'
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS'
export const JOB_SEARCH_FAIL= 'JOB_SEARCH_FAIL'

export const JOB_DETAILS_REQUEST = 'JOB_DETAIL_REQUEST'
export const JOB_DETAILS_SUCCESS = 'JOB_DETAIL_SUCCESS'
export const JOB_DETAILS_FAIL= 'JOB_DETAIL_FAIL'